- name: Add user maverik
  become: true
  ansible.builtin.user:
    name: maverik
    group: TOPGUN

- name: Add user charlie
  become: true
  ansible.builtin.user:
    name: charlie
    group: TOPGUN

- name: Add user goose
  become: true
  ansible.builtin.user:
    name: goose
    group: TOPGUN
