---

- name: Preconfigure iptables-persistent to auto-save rules
  debconf:
    name: iptables-persistent
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: boolean
  loop:
    - { question: 'iptables-persistent/autosave_v4', value: false }
    - { question: 'iptables-persistent/autosave_v6', value: true }
  become: true
  tags: firewall

- name: Install iptables-persistent for IPv6 rule persistence
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  become: true
  tags: firewall

- name: Ensure ip6tables default policies
  ansible.builtin.command: >
    ip6tables -P {{ item.key }} {{ item.value }}
  loop: "{{ ipv6_default_policies|dict2items }}"
  become: true
  tags: firewall

- name: Allow loopback on IPv6
  ansible.builtin.command: >
    ip6tables -A {{ item.chain }}
               {% if item.in_interface is defined %}-i {{ item.in_interface }}{% endif %}
               {% if item.out_interface is defined %}-o {{ item.out_interface }}{% endif %}
               -j {{ item.jump }}
  loop: "{{ ipv6_loopback }}"
  become: true
  tags: firewall

- name: Save ip6tables rules to persistent file
  ansible.builtin.shell: ip6tables-save > /etc/iptables/rules.v6
  become: true
  notify: Reload iptables-persistent
  tags: firewall


# --- Début de la section IPv4 ---

- name: Preconfigure iptables-persistent (IPv4 autosave)
  debconf:
    name: iptables-persistent
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: boolean
  loop:
    - { question: 'iptables-persistent/autosave_v4', value: true }
    - { question: 'iptables-persistent/autosave_v6', value: false }
  become: true
  tags: firewall

- name: Install iptables-persistent for IPv4 rule persistence
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  become: true
  tags: firewall

- name: Debug iptables -P INPUT DROP
  ansible.builtin.command: iptables -P INPUT DROP
  become: true
  tags: firewall

- name: Ensure iptables default policies (IPv4)
  ansible.builtin.command: >
    iptables -P {{ item.key }} {{ item.value }}
  loop: "{{ ipv4_default_policies|dict2items }}"
  become: true
  tags: firewall

- name: Apply base IPv4 rules (loopback, established, SSH, HTTP, HTTPS)
  ansible.builtin.command: >
    iptables -A {{ item.chain }} {{ item.rule }}
  loop: "{{ ipv4_base_rules }}"
  become: true
  tags: firewall

- name: Log dropped IPv4 packets
  ansible.builtin.command: >
    iptables -A INPUT -m limit --limit 5/min -j LOG
    --log-prefix "{{ ipv4_log_prefix }}" --log-level 4
  become: true
  tags: firewall

- name: Save iptables rules to persistent file (IPv4)
  ansible.builtin.command: iptables-save > /etc/iptables/rules.v4
  become: true
  notify: Reload iptables-persistent
  tags: firewall
