- name: Générer les secrets TOTP pour les utilisateurs concernés
  expect:
    command: sudo -H -u {{ item }} google-authenticator -t -d -f -r 3 -R 30 -w 3
    responses:
      'Do you want to disallow multiple uses of the same authentication token? \(y/n\)': 'y'
      'By default, tokens are good for 30 seconds. Do you want to do so? \(y/n\)': 'y'
      'Do you want to enable rate-limiting.*? \(y/n\)': 'y'
      'Do you want to update your "~/.google_authenticator" file? \(y/n\)': 'y'
      'Enter code from app.*': '-1'
    timeout: 10
  become: true
  args:
    chdir: "/home/{{ item }}"
    creates: "/home/{{ item }}/.google_authenticator"
  loop:
    - maverik
    - charlie