- name: Configure SSH server
  become: true
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart SSH

- name: Ensure SSH service is running and enabled
  become: true
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
