- name: Install required packages
  become: true
  ansible.builtin.apt:
    name:
      - openssh-server
      - libpam-google-authenticator
      - sudo
      - acl
    state: present
    update_cache: true
