---
- name: 'ARS DM4 DMZ infra setup'
  hosts: infra
  roles:
    - role: 'roles/nginx'
    - role: 'roles/openssh'
    - role: 'roles/apache'
      KeyTabPath: 'epitaf.keytab'
      apache_key: 'certificates/infra01.key'
      apache_cert: 'certificates/infra01.crt'
      wordpress_sql_user: 'user'
      wordpress_sql_pass: 'pass'
    - role: 'roles/firewall'
    - role: 'roles/fail2ban'
